name: "Digest OpenZH Data into CSV files"

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'
  schedule:
    - cron: '0 * * * *'  # Once an hour
jobs:
  digest:
    name: Download and digest data
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7']
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: 'true'
          python-version: ${{ matrix.python-version }}
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Install Conda Packages
        shell: pwsh
        run: conda install pandas
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Download and digest data
        shell: pwsh
        run: | 
          pwd
          cd ./python-scripts
          python3.7 digest_openzh.py
      - name: Install SSH Client 🔑
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy data to ddrobotec.github.io 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3-test
        with:
          BASE_BRANCH: master
          BRANCH: master
          FOLDER: python-scripts/output_openzh
          TARGET_FOLDER: covid19_openzh_data
          REPOSITORY_NAME: ddrobotec/ddrobotec.github.io
          CLEAN: true
          SSH: true # SSH must be set to true so the deploy action knows which protocol to deploy with.
          DEBUG: true