name: "Digest OpenZH Data into CSV files"

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  digest:
    name: Download and digest data
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7']
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: 'true'
          python-version: ${{ matrix.python-version }}
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Install Conda Packages
        shell: pwsh
        run: conda install pandas
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Download and digest data
        shell: pwsh
        run: | 
          pwd
          cd ./python-scripts
          python3.7 digest_openzh.py